### ISSUE TITLE
Deletes public/cache folder but wont create new

### ISSUE THREAD

**Issue by sqvist** [odan/twig-assets#12]
Hi, i have applied the "clear cache"-mechanism to a test project. 
It sure does clear the cache.

But it wont recreate the public/cache/ folder, i have to create it manually. 
I've checked the permissions, they are all clear... And SELinux is not issue.

As soon as i "mkdir public/cache/", everything works and the twig-assets is starting to produce cache.

**Comment by odan** [comment]
Hi @sqvist Thanks for the feedback. I will provide a fix for this issue.

**Comment by odan** [comment]
This issue should be fixed now. Please update to the latest version.

**Comment by sqvist** [comment]
@odan , works very well! Splendido!
