### ISSUE TITLE
Generate absolute url

### ISSUE THREAD

**Issue by codedge** [odan/twig-assets#17]
Is there a way to generate absolute assets URLs instead of relative ones?
Ideal would be if the base url for the assets could be specified somewhere.

Thanks for the nicely working package.

**Comment by odan** [comment]
Hi @codedge 

At the moment an abolsute url is not directly supported, because you can define a (relative or aboslute) base href in your html document like this:

```html
<base href="https://example.com/my-base-url-or-path/"/>
```

What do you plan to do?

**Comment by codedge** [comment]
Hmm, I see. I am not sure this will help me.

The problem is:
* Old project is refactored to some newer Slim 4 project
* Assets should be pulled from `BASEURL/assets/...`
* The project itself needs some initial param like `BASEURL/important-param/paramval`

In the current implementation the `asset` function delivers links with `BASEURL/important-param/assets`.

I hope you get  the point 😅

**Comment by codedge** [comment]
So the `<base href="..">` does the trick! Thanks for for the hint! 👍
