### ISSUE TITLE
Is it possibile to divide CSS from JS?

### ISSUE THREAD

**Issue by tobiascapin** [odan/twig-assets#20]
I would like to load CSS at the head block and scripts at the bottom of the page.
Is it possibile to divide two blocks or filter file by type?

**Comment by odan** [comment]
Yes, you can output the CSS and JS where you need it.

```twig
<html>
    <head>
        {{ assets({files: ['home/index.css']}) }}
    </head>
    <body>
        {{ assets({files: ['home/index.js']}) }}
    </body>
</html>
```

Here you can fine more advanced examples: https://github.com/odan/twig-assets#output-page-specific-assets

**Comment by tobiascapin** [comment]
Right, sorry I was misleaded by the layout example where there was a unique "assets" block for everything.
