### ISSUE TITLE
Twig error

### ISSUE THREAD

**Issue by drnasin** [odan/twig-assets#25]
Hi  @odan , I'm trying to use this in my slim4 project but I can't get it to work.

I keep getting 

Type: Twig\Error\LoaderError
Code: 0
Message: Unable to find template "cdn/assets/bootstrap.bundle.js" (looked into: C:\Users\antek\PhpstormProjects\kompcontrol/app/templates/shop).

I'm not sure as to why assets look into templates dr?

I use it like this in twig
{{ assets({files: ['cdn/assets/bootstrap.bundle.js']}) }}

But I get that error no matter what I do. I think the code is ok. I'm not sure about the base path setting as I'm not using the "Public dir"

My settings:
![image](https://user-images.githubusercontent.com/3784166/110216186-f03e7880-7ead-11eb-93fc-fc854b30aa1d.png)

Here is my dependency code

![image](https://user-images.githubusercontent.com/3784166/110216017-0ef03f80-7ead-11eb-9ae2-450d080122bf.png)

Middleware
![image](https://user-images.githubusercontent.com/3784166/110216113-9e95ee00-7ead-11eb-8be0-8fb4afd4b9d6.png)

Not sure what am I doing wrong. Seems ok. All the paths are correct.

Thank you for any help @odan !

**Comment by drnasin** [comment]
got it to work using

 $loader->addPath(SHOP_PATH, 'public');

{{ assets({files: ['@public/cdn/assets/bootstrap.bundle.js']}) }}

**Comment by odan** [comment]
This is good.
