### ISSUE TITLE
Cannot enable cache

### ISSUE THREAD

**Issue by tobiascapin** [odan/twig-assets#26]
The Last-Modified header is always set to now, the browser is always refreshing my assets.
The configuration $settings['assets']['cache_enabled'] key seems not to have effect.

**Comment by odan** [comment]
This component caches the assets only on the server side. It does not modify any header to control the client-side caching behavior. Have you tried to modify the response header in a custom middleware?

**Comment by tobiascapin** [comment]
I could not understand how the http request is driven to the cache file in the file system. Can you help me?

**Comment by odan** [comment]
The page specific assets will be compressed and cached (on the server) as soon as Twig renders the template with the `assets` helper function. The browser should then load these assets from the server only once.

**Comment by tobiascapin** [comment]
I have found that the cached file is touched after every template page load. I'm using apache2.4 and there are the If-Modified-Since and If-None-Match headers set. The E-tag is keeped, but the webserver somehow replies each time because the cache file timestamp is updated then the If-Modified-Since forces the reply.
These are the assets settings:
```
//assets
$settings['assets'] = [
    // Public assets cache directory
    'path' => $settings['root'] . '/public/cache',
    'url_base_path' => '/cache/',
    'url_apply_base_path' => true,
    // Cache settings
    'cache_enabled' => true,
    'cache_path' => $settings['temp'],
    'cache_name' => 'assets-cache',
    //  Should be set to 1 (enabled) in production
    'minify' => 1,
];

```
Can it be related to cache_lifetime=0 setting or is something related with FilesystemAdapter?
As far as I saw, the cached file is saved to file for each template render.

**Comment by odan** [comment]
The FilesystemAdapter caches only when the `cache_path` is defined. In your case the cache_path comes from `$settings['temp']`.
Are you sure, that the value of `$settings['temp']` is not empty?

**Comment by tobiascapin** [comment]
Yes, it is set as (approot)/tmp. And there are some files inside.
It looks like `$this->publicCache->createCacheBustedUrl` is called for each templated render? Am I wrong?
Inside that method I have found file_put_contents for each call without any bypass in case of cache hit.

**Comment by odan** [comment]
I would guess this is because of the CSP (content security policy) feature that has been added in the last version. The `nonce` must be unique per request. Maybe this is a bug. I have to check it.

**Comment by odan** [comment]
This issue should be fixed now in the latest version.
