### ISSUE TITLE
Function to clear cache?

### ISSUE THREAD

**Issue by SaphiLC** [odan/twig-assets#3]
is there any function to clear both cache and assets folder?

**Comment by odan** [comment]
Hi @SaphiLC 

Currently there is no such function. I could imagine adding this method.
Should this function also be available in the console?

**Comment by SaphiLC** [comment]
i intend to use it as a button in the control panel, but yeah a console command could be nice to have too :)

also, some events would be nice, like, before creating new assets, so you can fire the clean up function, to have a clean assets folder (had like 300 old files there xD thats why im asking this question)

**Comment by odan** [comment]
A new function to clear the cache has beed added:

https://github.com/odan/twig-assets#clearing-the-cache
