### ISSUE TITLE
Subfolder URL error for assets cache

### ISSUE THREAD

**Issue by tobiascapin** [odan/twig-assets#31]
I have an application installed in a subfolder, I have to use a {{base_path()}} in all html url tags to create the correct relatives URL.
I'm facing an issue with this library because the cache folder is not mapped with base_path prefix, my current settings are:

```
$settings['assets'] = [
    // Public assets cache directory
    'path' => $settings['root'] . '/public/cache',
    'url_base_path' => 'cache/',
    // Cache settings
    'cache_enabled' => true,
    'cache_lifetime'=>0,
    'cache_path' => $settings['temp'],
    'cache_name' => 'assets-cache',
    //  Should be set to 1 (enabled) in production
    'minify' => 0,
];
```

From this page http://localhost/myapp/
the loaded cache works, looking into http://localhost/myapp/cache
but if I use a subfolder like this: http://localhost/myapp/auth/login
the rendered assets has this URL http://localhost/myapp/auth/cache and it is not found.

I tried to change thesetting  'url_base_path' to '{{base_path()}}/cache/', but if doesn't work.

**Comment by odan** [comment]
Hi @tobiascapin 

Can you try this first?

* https://github.com/odan/twig-assets/issues/5#issuecomment-440785489

**Comment by tobiascapin** [comment]
Thanks for the tip, finally I solved prependig the url_base_path setting with the Slim basepath value.
