### ISSUE TITLE
"Twig\TwigFunction::setArguments()" method is deprecated, use "Twig\TwigFunction::withDynamicArguments()" instead.

### ISSUE THREAD

**Issue by NetesiCTO** [odan/twig-assets#36]
Hello,
My Slim project says "Twig\TwigFunction::setArguments()" method is deprecated, use "Twig\TwigFunction::withDynamicArguments()" instead on line 25 in file /vendor/symfony/deprecation-contracts/function.php

**Comment by NetesiCTO** [comment]
I see in your code that maybe the problem was  $function->setArguments([]); on /src
/TwigAssetsExtension.php line 42

**Comment by odan** [comment]
Hi! This should be fixed now in the latest version (4.0.0).
