### ISSUE TITLE
How can we disable the cache feature?

### ISSUE THREAD

**Issue by ghost** [odan/twig-assets#6]
Hi!

We would like to disable the cache feature but the cache_enabled option is never used in the code. Is there any other way to disable this feature?

Thank you!

**Comment by odan** [comment]
Hi!

Thank you, I will remove the key `cache_enabled` from the readme.

It's possible to disable the internal cache by changing the `cache_path` to an empty string.

Example:

```php
'cache_path' => '', // disable internal cache
```

**Comment by ghost** [comment]
Hi!

Thank you, it's work! :)
