### ISSUE TITLE
Twig-view & Deprecated classes

### ISSUE THREAD

**Issue by Arkshine** [odan/twig-assets#8]
Hi, 

A few days ago, Twig-View component has been updated and Twig requirement version bumped due to a vulnerability. It results in the replacement of deprecated classes which Twig-asset is using: https://github.com/slimphp/Twig-View/releases/tag/2.5.0.

**Comment by odan** [comment]
Hi! This library has no dependencies to `slim/twig-view`. See here in: [composer.json](https://github.com/odan/twig-assets/blob/master/composer.json). Only the `"twig/extensions": "^1.5"` is required and [up to date](https://github.com/twigphp/Twig-extensions/releases).

**Comment by Arkshine** [comment]
Well, yes, but you are documenting the use of Twig-view. I thought something could be done to avoid those warnings when you're running the latest stable versions. If anything, documenting it could be welcomed.

Looks like they are working on v2: https://github.com/twigphp/Twig-extensions/pull/236

Thanks anyway, I understand. Guess will fork your project then since I would like to avoid downgrading and locking twig-view to 2.4.0.

**Comment by odan** [comment]
Ok I see. The class names should be fixed now.
