### ISSUE TITLE
twig-assets and slim4

### ISSUE THREAD

**Issue by killua-eu** [odan/twig-assets#9]
Hi Daniel, would you mind including some examples to get twig-assets work with slim4, or maybe show that in your hatching https://github.com/odan/slim4-skeleton ? Thanks lots in advance, cheers, P.

**Comment by odan** [comment]
Hi @killua-eu 

Yes, this would be the next step for the `slim4-skeleton` project. I'm working on it. Would be nice if you create an issue here: https://github.com/odan/slim4-skeleton/issues Thanks.

**Comment by killua-eu** [comment]
Done! Closing this ticket, thanks lots in advance.
